version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always

  backend:
    build: ./backend
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend/article_library:/app/article_library

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      - SUBDOMAINS=nartdg-blog
      - TOKEN=edad3adb-2d07-44e3-aa75-f4c2dda5c658
      - LOG_FILE=true
    restart: unless-stopped

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt