version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always

  backend:
    build: ./backend
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend/article_library:/app/article_library

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml
    command: tunnel --no-autoupdate run --token eyJhIjoiYzNhODNmZTY1NzBmYTlmN2JhNTQ3ZDFlNjliOTFlMjQiLCJ0IjoiYjk3OTZhZTgtMWNjYy00NTA5LTgzMWUtZGIzOGVhMjM5NzBhIiwicyI6IlpERTNaRFEzT1dJdE0yTTRNUzAwWVRFeUxXSXpPREF0TjJFeE5EQTVPV0prTkRGaSJ9