services:
  redis:
    image: redis:alpine
    restart: always

  backend:
    build: ./backend
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "30080:4321"
    depends_on:
      - backend